services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my_network
  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my_network

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/agvincen/data/mariadb
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/agvincen/data/wordpress
      o: bind

networks:
  my_network:
    driver: bridge